USE ROLE ACCOUNTADMIN;

SHOW PARAMETERS LIKE 'TIMEZONE' IN ACCOUNT;      -- America/Los_Angeles
ALTER ACCOUNT SET TIMEZONE = 'UTC';

CREATE RESOURCE MONITOR IF NOT EXISTS TRIAL_GUARD
  WITH CREDIT_QUOTA = 40
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER ACCOUNT SET RESOURCE_MONITOR = TRIAL_GUARD;

SHOW PARAMETERS LIKE 'TIMEZONE' IN ACCOUNT;      -- UTC
SHOW RESOURCE MONITORS;