USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS WEATHER_DB
      -- DATA_RETENTION_TIME_IN_DAYS = 1
    COMMENT = 'OpenWeather ingestion, dbt transformations';

DROP SCHEMA IF EXISTS WEATHER_DB.PUBLIC;

CREATE SCHEMA IF NOT EXISTS WEATHER_DB.RAW
    COMMENT = 'Landed JSON as VARIANT. Never modified, only appended';
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.STAGING
    COMMENT = 'dbt staging models, one per source entity';
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.ANALYTICS
    COMMENT = 'dbt marts, the tables people query';
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.INTERMEDIATE
    COMMENT = 'dbt intermediate models';
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.REPORTS
    COMMENT = 'dbt report models';

SHOW SCHEMAS IN DATABASE WEATHER_DB;