USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS WEATHER_ENGINEER COMMENT = 'dbt and Airflow service role';

USE ROLE SECURITYADMIN;
GRANT ROLE WEATHER_ENGINEER TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE WEATHER_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE WEATHER_ENGINEER;
GRANT USAGE ON DATABASE WEATHER_DB TO ROLE WEATHER_ENGINEER;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA WEATHER_DB.RAW TO ROLE WEATHER_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA WEATHER_DB.STAGING TO ROLE WEATHER_ENGINEER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA WEATHER_DB.MARTS TO ROLE WEATHER_ENGINEER;

GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA WEATHER_DB.RAW TO ROLE WEATHER_ENGINEER;

SHOW GRANTS TO ROLE WEATHER_ENGINEER;
SHOW FUTURE GRANTS IN SCHEMA WEATHER_DB.RAW;