USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS WEATHER_SVC
    TYPE = SERVICE
    DEFAULT_ROLE = WEATHER_ENGINEER
    DEFAULT_WAREHOUSE = TRANSFORM_WH
    DEFAULT_NAMESPACE = WEATHER_DB.STAGING
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoCKUkE5yN1ObhdQAuJwh
fdvKVyxRDHBx7KNx0Tlj6utgJg6E+9fbrKmS87A2Fcslh5OjA6aq1HIweYp4Icsw
uPn/IW/Hm+33nwlURoBxG/eOqJh7wYkaigsd24G4pT4GLaCKA5gjMtZMsyt7lQDr
nGbWBznRF2Sh/iZ4JEjQfDm+V0XQDGUXMYq1yp3ksezeRI+wQm1tXHDibCTPAvf8
719obb2TnUvSYsbHIe6SF0jGteZytgZL9GVOvYH050fOyt+yDkOWpGDo6NCh4pFw
syev5VTHyTeiWhEAGaXwWKh1z4XX4wwFpetKryiGJIOULfktOdE6+x9buh2kgUFo
swIDAQAB'
    COMMENT = 'dbt and Airflow. Key pair only, no password';

USE ROLE SECURITYADMIN;
GRANT ROLE WEATHER_ENGINEER TO USER WEATHER_SVC;

DESC USER WEATHER_SVC;
    