USE ROLE WEATHER_ENGINEER;
USE SCHEMA WEATHER_DB.RAW;

CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_HEADER
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('');

CREATE STAGE IF NOT EXISTS RAW.EXPORT_STAGE
  FILE_FORMAT = RAW.CSV_HEADER;


-- JSON SETUP
USE ROLE WEATHER_ENGINEER;
USE SCHEMA WEATHER_DB.RAW;

CREATE FILE FORMAT IF NOT EXISTS RAW.JSON
    TYPE = JSON
    STRIP_OUTER_ARRAY = TRUE;

ALTER FILE FORMAT WEATHER_DB.RAW.JSON RENAME TO WEATHER_DB.RAW.JSON_FORMAT;

CREATE STAGE IF NOT EXISTS RAW.JSON_STAGE
  FILE_FORMAT = RAW.JSON_FORMAT;

LIST @RAW.JSON_STAGE;