USE ROLE WEATHER_ENGINEER;
USE WAREHOUSE LOAD_WH;
USE SCHEMA WEATHER_DB.RAW;

COPY INTO RAW.WEATHER_FORECAST
  FROM @RAW.EXPORT_STAGE/weather_forecast.csv.gz
  ON_ERROR = ABORT_STATEMENT
  PURGE = TRUE;

SELECT * FROM RAW.WEATHER_FORECAST
LIMIT 10;

SELECT file_name, status, row_count, last_load_time
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'WEATHER_FORECAST',
  START_TIME => DATEADD(hour, -1, CURRENT_TIMESTAMP())));


USE ROLE WEATHER_ENGINEER;
USE WAREHOUSE LOAD_WH;
USE SCHEMA WEATHER_DB.RAW;

LIST @JSON_STAGE;

COPY INTO WEATHER_DB.RAW.FORECAST_JSON (payload, loaded_at, source_file)
FROM (
    SELECT $1, CURRENT_TIMESTAMP(), METADATA$FILENAME
    FROM @WEATHER_DB.RAW.JSON_STAGE/output.json.gz
    )
FILE_FORMAT = (FORMAT_NAME = WEATHER_DB.RAW.JSON_FORMAT)
PURGE = TRUE;
